import type { NextPage } from 'next';
import Head from 'next/head';
//import { useSession, signIn, signOut } from 'next-auth/react';

const Home: NextPage = () => {
  
  //const loginHandler = () => {
		//if(status === 'authenticated') {
			//console.log(session.user.email)
			//signOut()
		//}
		//else signIn()
    
    
	
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default Home;
